version: '3'

services:
  # Database
  db:
    image: mariadb
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - the7ofdiamonds.tech_sites

  php-fpm:
    build:
      context: .
    container_name: php-fpm
    restart: unless-stopped
    ports:
      - '9000:9000'
    networks:
      - the7ofdiamonds.tech_sites
    volumes:
          - ./wordpress:/var/www/wordpress

  nginx-wordpress:
    depends_on:
      - db
      - php-fpm
    image: nginx-wordpress
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./wordpress:/var/www/wordpress
    ports:
      - 8000:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    networks:
      - the7ofdiamonds.tech_sites

networks:
  the7ofdiamonds.tech_sites:
    name: the7ofdiamonds.tech_sites

volumes:
  mysql:
  wordpress:
