version: '3'

services:      
  mysql:
    container_name: mysql-db
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - the7ofdiamonds.tech_sites
      - api.orbfin.tech

  php:
    container_name: php
    build:
      context: ./php
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/wordpress:/var/www/wordpress
      - ./php/wordpress/wp-content/debug.log:/var/log/debug.log
    networks:
      - the7ofdiamonds.tech_sites
      - api.orbfin.tech
    environment:
      WORDPRESS_DB_HOST: mysql-db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ALLOW_MULTISITE', true);
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', '${DOMAIN_ONE}');
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
        define('WP_DEBUG', 'true');
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('WP_MEMORY_LIMIT', '2048M');
    env_file: .env

  nginx:
    container_name: nginx-server
    image: nginx:latest
    restart: always
    depends_on:
      - php
    ports:
      - ${NGINX_PORT_ONE}:80
      - ${NGINX_PORT_ONE_SECURE}:443
    volumes:
      - ./nginx/secure.conf:/etc/nginx/secure.conf
      - ./nginx/wordpress.conf:/etc/nginx/wordpress.conf
      - ./nginx/templates/:/etc/nginx/templates
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./php/wordpress:/var/www/wordpress
    networks:
      - the7ofdiamonds.tech_sites
      - api.orbfin.tech
    env_file: .env

networks:
  the7ofdiamonds.tech_sites:
    name: the7ofdiamonds.tech_sites
    external: true

  api.orbfin.tech:
    name: api.orbfin.tech
    external: true
    
volumes:
  mysql_data:
  wordpress:
  pgdata: