version: '3'

services:
  # Database
  db:
    image: mariadb
    volumes:
      - MySQL:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - THE7OFDIAMONDS.TECH_SITES

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-fpm-alpine
    restart: always
    volumes:
      - ./wordPress:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    links:
      - db
    networks:
      - THE7OFDIAMONDS.TECH_SITES

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
    ports:
      - 8000:80
    links:
      - wordpress
    networks:
      - THE7OFDIAMONDS.TECH_SITES


networks:
  THE7OFDIAMONDS.TECH_SITES:
    name: THE7OFDIAMONDS.TECH_SITES
volumes:
  MySQL:
  WordPress: