version: '3'

services:      
  mysql:
    container_name: mysql-db
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - the7ofdiamonds.tech_sites

  php:
    container_name: php
    build:
      context: ./php
    restart: always
    depends_on:
    - mysql
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - ${PHP_PORT}:${PHP_PORT}
    networks:
      - the7ofdiamonds.tech_sites
      - api.orbfin.tech
    env_file: .env

  nginx:
    container_name: the7ofdiamonds.development
    # image: nginx:latest
    build:
      context: ./nginx
      dockerfile: WordPress.Dockerfile
    restart: always
    depends_on:
    - php
    ports:
      - ${NGINX_PORT_ONE}:80
      - ${NGINX_PORT_ONE_SECURE}:443
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./wordpress:/var/www/wordpress
    hostname: the7ofdiamonds.development
    networks:
      - the7ofdiamonds.tech_sites
      - api.orbfin.tech
    env_file: .env

networks:
  the7ofdiamonds.tech_sites:
    name: the7ofdiamonds.tech_sites

  api.orbfin.tech:
    name: api.orbfin.tech
    external: true
    
volumes:
  mysql:
  wordpress:
  pgdata:
