version: '3'

services:
  nginx-wordpress:
    build:
      context: .
    image: nginx-wordpress
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ../wordpress:/var/www/wordpress
    ports:
      - 8000:80
    networks:
      - THE7OFDIAMONDS.TECH_SITES

networks:
  THE7OFDIAMONDS.TECH_SITES:
    name: THE7OFDIAMONDS.TECH_SITES