version: '3'

services:
  # Database
  mysql-db:
    image: mariadb
    volumes:
      - ../mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - the7ofdiamonds.tech_sites

  php:
    container_name: php
    build:
      context: ../php
    restart: unless-stopped
    depends_on:
    - mysql-db
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/wordpress.conf:/etc/nginx/wordpress.conf
      - ../nginx/logs:/var/log/nginx
      - ../nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ../nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ../nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ../nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ../nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./:/var/www/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - "9000:9000"
    networks:
      - the7ofdiamonds.tech_sites

  nginx:
    container_name: the7ofdiamonds.development
    build:
      context: ../nginx
      dockerfile: WordPress.Dockerfile
    restart: always
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www/wordpress

    networks:
      - the7ofdiamonds.tech_sites

networks:
  the7ofdiamonds.tech_sites:
    name: the7ofdiamonds.tech_sites

volumes:
  mysql:
  wordpress:
