FROM php:8.3-fpm

# Install necessary packages
RUN apt-get update && apt-get install -y \
    git \
    autoconf \
    automake \
    libtool \
    build-essential \
    libhiredis-dev \
    libzip-dev \
    libpq-dev \
    libpng-dev \
    libicu-dev \
    libsodium-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install phpiredis
RUN git clone --depth 1 https://github.com/nrk/phpiredis.git /tmp/phpiredis \
    && cd /tmp/phpiredis \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && rm -rf /tmp/phpiredis \
    && docker-php-ext-enable phpiredis

# Install PHP extensions
RUN docker-php-ext-install zip mysqli pdo pdo_mysql pdo_pgsql bcmath exif gd intl opcache sodium

# Download and set up WordPress
RUN curl -o wordpress.tar.gz -SL https://wordpress.org/latest.tar.gz \
    && tar -xzf wordpress.tar.gz -C /var/www \
    && rm wordpress.tar.gz \
    && chown -R www-data:www-data /var/www/wordpress
  
WORKDIR /var/www/wordpress

RUN composer require vlucas/phpdotenv

COPY www.conf /usr/local/etc/php-fpm.d

CMD ["php-fpm"]