FROM php:8.2-fpm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y wget unzip libzip-dev git libpq-dev libpng-dev libicu-dev libsodium-dev

RUN docker-php-ext-install zip mysqli pdo pdo_mysql pdo_pgsql bcmath exif gd intl opcache sodium

WORKDIR /var/www

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    rm composer-setup.php

RUN wget https://wordpress.org/latest.tar.gz && \
    tar -xzvf latest.tar.gz && \
    rm latest.tar.gz && \
    chown -R www-data:www-data /var/www/wordpress
  
WORKDIR /var/www/wordpress

RUN composer require vlucas/phpdotenv

COPY www.conf /usr/local/etc/php-fpm.d

CMD ["php-fpm"]
